[project]
name = "causal-moe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "clearml>=2.0.1",
    "scipy>=1.15.3",
    "tiktoken>=0.9.0",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "transformers>=4.52.4",
]
